name = "FormattedTables"
uuid = "1e5e90d4-ce83-11e8-20f2-5351f6268164"
authors = ["Tom Lee <contact@tomlee.com.au>"]
version = "0.2.0-DEV"

[deps]
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DataFrames", "CSV"]
